language: go
go: 1.13.x
dist: trusty
os: linux

env:
- GO111MODULE=on

install:
- go get golang.org/x/lint/golint

script:
- make all release

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: NYYuiAof28yz1lTFeGL+qDHgVCpDiwsWB1zU/7uw34nOrp/P4sfiA2Bv7BcY2MA7nDmiuLYeWLlUsiieeOHL6Q2ZTWCwom495OGX0tpJsvAd5Q2q2D7+ofEEUHPokEmtF+flwNpUeZ6xV5WhqMF1tktCiBiw8CNvb32b81Aej89rf/1Fx4kXzmLTGlP4nvcL79nQ9UObMQp94P3YoUVCiS8CiHnkf/ElY2fmGtW8ondaDZiOyKyNDbuiS1fT3dMwjiTsyBr6SiZK5xKU/bkq0f5zotdYVI3Y28wyhItPYtKHyAmG2VhWms5YWIiNGzDNIsha8JlrGqyKsiM7CItRRzJAGJNwFu+LF3DqT5ruM46iZD9B3IGxAWfmZBM3wTTuwFhQEQXz933k3BhpBh7ayI/ba+wfdZ4SsODauFGve5TAynuA2AmbHcsXH5Aui6I1bEfz7TXmxXZwA+bAQKgDlFDIYYPAF72MtYfRm/0xut8xPXs/l7rUnjXZabj0PqezNoshMK+yUTeYxiWvA3k6jUptsHywi1oC7dF/yvRUD5n7q+SOfZ4296DJo9uyVJ0fM54WFWJrsLm6yttCzkOr/qCAuPb/Ge9f7xHuTaTkCAY3WbtzyAa2UxhqtQ60qTub6d+DW46U3DYMaH0UMMiq6hmeRXT2I0+6EVWjAtSg/EE=
  file_glob: true
  file: output/instana-terraform-dump*
  on:
    tags: true
    repo: gessnerfl/instana-terraform-dump
